# Generated by Django 4.2 on 2023-06-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configrations', '0002_alter_myuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=251, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=251, null=True),
        ),
    ]
